version: '3.3'

networks:
  prometheus:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    user: root
    volumes:
      - /data/monitoring/prometheus-server/:/prometheus/
      - /etc/prometheus/:/etc/prometheus/
    networks:
      - prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://prometheus-server.local/prometheus'


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: root
    volumes:
      - /data/monitoring/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - prometheus 
    restart: always

  node-exporter:
    image: prom/node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - prometheus
    restart: always

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - prometheus
    restart: always
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager
    user: root
    ports:
      - 9093:9093
    volumes:
      - /etc/alertmanager/:/etc/alertmanager/
    networks:
      - prometheus
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
