global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'root@prometheus-server.local'
  smtp_auth_username: 'testuser@gmail.com'
  smtp_auth_password: 'yourpassword'
  smtp_require_tls: true
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 1h
  receiver: jm-alerts

  routes:
  - match:
      job: prometheus-server
    receiver: jm-alerts
    repeat_interval: 1h

receivers:
- name: 'jm-alerts'
  email_configs:
  - to: 'alerts-mailbox@gmail.com'
